version: '3.4'
services:
    vertx-keycloak:
        image: quay.io/keycloak/keycloak:24.0.2
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        volumes:
            - ./realm.json:/opt/keycloak/data/import/realm.json
        network_mode: host
        #restart: always
        command: ["start-dev", "--http-port=8001", "--verbose", "--import-realm"]

